import { defaultTheme } from "../themes/defaultTheme";
import type { SmartTemplateDefinition, TemplateDefinition, ThemeTokens } from "../types";

type TemplateInput = Omit<TemplateDefinition, "version" | "status" | "theme"> & {
  theme: Partial<ThemeTokens> & Pick<ThemeTokens, "colors">;
};

const theme = (colors: ThemeTokens["colors"], fontFamily = "inherit"): ThemeTokens => ({
  ...defaultTheme,
  colors,
  typography: { ...defaultTheme.typography, fontFamily },
});

const badgeByCategory: Record<TemplateDefinition["category"], TemplateDefinition["badge"]> = {
  minimal: "Novo",
  creator: "Popular",
  business: "Mais usado",
  restaurant: "Novo",
  clinic: "Novo",
  therapy: "Novo",
  academy: "Novo",
  law: "Novo",
  beauty: "Novo",
  store: "Popular",
  portfolio: "Novo",
  premium: "Premium",
};

const bestForByCategory: Record<TemplateDefinition["category"], string> = {
  minimal: "perfis objetivos",
  creator: "criadores e influenciadores",
  business: "serviços profissionais",
  store: "lojas e catálogos",
  restaurant: "restaurantes e pedidos",
  clinic: "clínicas e consultórios",
  therapy: "terapeutas e psicólogos",
  academy: "academias e personal trainers",
  law: "advogados e escritórios jurídicos",
  beauty: "beleza e bem-estar",
  portfolio: "portfólios criativos",
  premium: "marcas que buscam sofisticação",
};

const define = (template: TemplateInput): TemplateDefinition => ({
  ...template,
  badge: template.badge ?? badgeByCategory[template.category],
  bestFor: template.bestFor ?? bestForByCategory[template.category],
  version: "1.0.0",
  status: "active",
  theme: theme(template.theme.colors, template.theme.typography?.fontFamily),
});

const displayFont = '"Poppins", "Inter", ui-sans-serif, system-ui, sans-serif';

const restaurantSmart: SmartTemplateDefinition = {
  niche: "restaurant",
  demo: {
    name: "Casa Brasa",
    description: "Cozinha afetiva e fogo lento.",
    heroLabel: "Peça hoje",
  },
  blocks: [
    {
      id: "hero",
      type: "hero",
      name: "Capa",
      description: "Imagem principal",
      required: true,
      defaultOrder: 0,
      canHide: false,
      canReorder: false,
      variants: ["photographic"],
    },
    {
      id: "profile",
      type: "profile",
      name: "Restaurante",
      description: "Marca e descrição",
      required: true,
      defaultOrder: 1,
      canHide: false,
      canReorder: false,
      variants: ["editorial"],
    },
    {
      id: "menu",
      type: "menu",
      name: "Cardápio",
      description: "Pratos em destaque",
      required: true,
      defaultOrder: 2,
      canHide: false,
      canReorder: true,
      variants: ["editorial"],
      restrictedTo: ["restaurant"],
    },
    {
      id: "delivery",
      type: "delivery",
      name: "Delivery",
      description: "Pedido e entrega",
      required: false,
      defaultOrder: 3,
      canHide: true,
      canReorder: true,
      variants: ["primary"],
      restrictedTo: ["restaurant"],
    },
    {
      id: "footer",
      type: "footer",
      name: "Rodapé",
      description: "Assinatura",
      required: true,
      defaultOrder: 4,
      canHide: false,
      canReorder: false,
      variants: ["refined"],
    },
  ],
};
const clinicSmart: SmartTemplateDefinition = {
  niche: "clinic",
  demo: {
    name: "Clínica Horizonte",
    description: "Cuidado humano em cada consulta.",
    heroLabel: "Agende sua consulta",
  },
  blocks: [
    {
      id: "hero",
      type: "hero",
      name: "Capa institucional",
      description: "Apresentação",
      required: true,
      defaultOrder: 0,
      canHide: false,
      canReorder: false,
      variants: ["institutional"],
    },
    {
      id: "profile",
      type: "profile",
      name: "Profissional",
      description: "Perfil e confiança",
      required: true,
      defaultOrder: 1,
      canHide: false,
      canReorder: false,
      variants: ["clinical"],
    },
    {
      id: "specialties",
      type: "specialties",
      name: "Especialidades",
      description: "Serviços e tratamentos",
      required: false,
      defaultOrder: 2,
      canHide: true,
      canReorder: true,
      variants: ["specialty-cards"],
      restrictedTo: ["clinic"],
    },
    {
      id: "contact",
      type: "contact",
      name: "Agendamento",
      description: "Contato principal",
      required: true,
      defaultOrder: 3,
      canHide: false,
      canReorder: true,
      variants: ["quiet-cta"],
    },
    {
      id: "footer",
      type: "footer",
      name: "Rodapé",
      description: "Institucional",
      required: true,
      defaultOrder: 4,
      canHide: false,
      canReorder: false,
      variants: ["institutional"],
    },
  ],
};
const storeSmart: SmartTemplateDefinition = {
  niche: "store",
  demo: {
    name: "Ateliê Rua 12",
    description: "Peças para transformar o dia a dia.",
    heroLabel: "Ver novidades",
  },
  blocks: [
    {
      id: "hero",
      type: "hero",
      name: "Banner",
      description: "Oferta principal",
      required: true,
      defaultOrder: 0,
      canHide: false,
      canReorder: false,
      variants: ["promotional"],
    },
    {
      id: "profile",
      type: "profile",
      name: "Marca",
      description: "Posicionamento",
      required: true,
      defaultOrder: 1,
      canHide: false,
      canReorder: false,
      variants: ["store"],
    },
    {
      id: "catalog",
      type: "catalog",
      name: "Vitrine",
      description: "Produtos em destaque",
      required: true,
      defaultOrder: 2,
      canHide: false,
      canReorder: true,
      variants: ["product-grid"],
      restrictedTo: ["store"],
    },
    {
      id: "offers",
      type: "offers",
      name: "Ofertas",
      description: "Destaques",
      required: false,
      defaultOrder: 3,
      canHide: true,
      canReorder: true,
      variants: ["banner"],
      restrictedTo: ["store"],
    },
    {
      id: "footer",
      type: "footer",
      name: "Rodapé",
      description: "Loja",
      required: true,
      defaultOrder: 4,
      canHide: false,
      canReorder: false,
      variants: ["store"],
    },
  ],
};

export const templateManifest: TemplateDefinition[] = [
  define({
    id: "default",
    slug: "default",
    name: "Bio essencial",
    description: "O visual atual da sua página.",
    category: "minimal",
    theme: {
      colors: {
        background: "#ffffff",
        surface: "#f8fafc",
        text: "#0f172a",
        muted: "#64748b",
        primary: "#6b3fff",
      },
    },
    layout: "vertical",
    components: ["banner", "profile", "links", "pix", "footer"],
    componentVariants: {
      banner: "default",
      profile: "default",
      links: "default",
      pix: "default",
      footer: "default",
    },
    supportedFeatures: ["profile", "links", "whatsapp", "pix"],
  }),
  define({
    id: "minimal-light",
    slug: "minimal-light",
    name: "Bio minimalista",
    description: "Leve, claro e direto ao ponto.",
    category: "minimal",
    theme: {
      colors: {
        background: "#ffffff",
        surface: "#f8fafc",
        text: "#0f172a",
        muted: "#64748b",
        primary: "#4f46e5",
      },
    },
    layout: "minimal",
    components: ["profile", "links", "footer"],
    componentVariants: { profile: "default", links: "minimal", footer: "discreet" },
    supportedFeatures: ["profile", "links", "socials"],
  }),
  define({
    id: "minimal-ink",
    slug: "minimal-ink",
    name: "Bio noturna",
    description: "Minimalismo escuro com presença marcante.",
    category: "minimal",
    theme: {
      colors: {
        background: "#111827",
        surface: "#1f2937",
        text: "#f9fafb",
        muted: "#cbd5e1",
        primary: "#a78bfa",
      },
    },
    layout: "minimal",
    components: ["profile", "links", "footer"],
    componentVariants: { profile: "business", links: "glass", footer: "discreet" },
    supportedFeatures: ["profile", "links", "socials"],
  }),
  define({
    id: "creator-bold",
    slug: "creator-bold",
    name: "Influenciador",
    description: "Visual expressivo para conteúdo e comunidade.",
    category: "creator",
    theme: {
      colors: {
        background: "#fff7ed",
        surface: "#ffffff",
        text: "#431407",
        muted: "#9a3412",
        primary: "#ea580c",
      },
    },
    layout: "creator",
    components: ["banner", "profile", "links", "footer"],
    componentVariants: {
      banner: "compact",
      profile: "overlapping-banner",
      links: "elevated",
      footer: "discreet",
    },
    supportedFeatures: ["profile", "links", "socials", "whatsapp"],
  }),
  define({
    id: "creator-soft",
    slug: "creator-soft",
    name: "Comunidade",
    description: "Uma apresentação acolhedora para sua audiência.",
    category: "creator",
    theme: {
      colors: {
        background: "#fdf2f8",
        surface: "#ffffff",
        text: "#500724",
        muted: "#9d174d",
        primary: "#db2777",
      },
    },
    layout: "cards",
    components: ["banner", "profile", "links", "pix", "footer"],
    componentVariants: {
      banner: "compact",
      profile: "overlapping-banner",
      links: "glass",
      pix: "highlighted",
      footer: "discreet",
    },
    supportedFeatures: ["profile", "links", "socials", "pix"],
  }),
  define({
    id: "business-modern",
    slug: "business-modern",
    name: "Saúde profissional",
    description: "Visual claro e humano para clínicas, consultórios e dentistas.",
    category: "business",
    badge: "Novo",
    bestFor: "clínicas, consultórios e profissionais de saúde",
    theme: {
      colors: {
        background: "#f5f9ff",
        surface: "#ffffff",
        text: "#0b2545",
        muted: "#4b6584",
        primary: "#0e7c86",
      },
      typography: { fontFamily: displayFont } as ThemeTokens["typography"],
    },
    layout: "clinic",
    components: ["profile", "links", "pix", "footer"],
    componentVariants: {},
    supportedFeatures: ["profile", "links", "whatsapp", "pix", "services"],
  }),
  define({
    id: "business-classic",
    slug: "business-classic",
    name: "Profissional",
    description: "Sóbrio e confiável para atendimento profissional.",
    category: "business",
    theme: {
      colors: {
        background: "#f1f5f9",
        surface: "#ffffff",
        text: "#172554",
        muted: "#475569",
        primary: "#1d4ed8",
      },
    },
    layout: "vertical",
    components: ["banner", "profile", "links", "pix", "footer"],
    componentVariants: {
      banner: "default",
      profile: "business",
      links: "minimal",
      pix: "highlighted",
      footer: "discreet",
    },
    supportedFeatures: ["profile", "links", "whatsapp", "pix"],
  }),
  define({
    id: "store-showcase",
    slug: "store-showcase",
    name: "Loja online",
    description: "Pequena loja online com produtos em destaque.",
    category: "store",
    smart: storeSmart,
    badge: "Novo",
    bestFor: "lojas, revendedoras e catálogos de produtos",
    theme: {
      colors: {
        background: "#fafaf7",
        surface: "#ffffff",
        text: "#111827",
        muted: "#6b7280",
        primary: "#111827",
      },
      typography: { fontFamily: displayFont } as ThemeTokens["typography"],
    },
    layout: "storefront",
    components: ["profile", "links", "pix", "footer"],
    componentVariants: {},
    supportedFeatures: ["profile", "links", "whatsapp", "pix", "products"],
  }),
  define({
    id: "restaurant-menu",
    slug: "restaurant-menu",
    name: "Restaurante",
    description: "Cardápio editorial e quente para restaurantes e cafés.",
    category: "restaurant",
    smart: restaurantSmart,
    badge: "Novo",
    bestFor: "restaurantes, cafés e delivery",
    theme: {
      colors: {
        background: "#09070f",
        surface: "#15101f",
        text: "#f7f4ff",
        muted: "#b9afc9",
        primary: "#8b3ff2",
      },
      typography: { fontFamily: displayFont } as ThemeTokens["typography"],
    },
    layout: "restaurant",
    components: ["profile", "links", "pix", "footer"],
    componentVariants: {},
    supportedFeatures: ["profile", "links", "whatsapp", "pix", "menu"],
  }),
  define({
    id: "clinic-care",
    slug: "clinic-care",
    name: "Clínica",
    description: "Apresentação clara e confiável para clínicas e dentistas.",
    category: "clinic",
    smart: clinicSmart,
    badge: "Novo",
    bestFor: "clínicas, dentistas e consultórios",
    theme: {
      colors: {
        background: "#eef7f7",
        surface: "#ffffff",
        text: "#183b42",
        muted: "#55767b",
        primary: "#177e89",
      },
      typography: { fontFamily: displayFont } as ThemeTokens["typography"],
    },
    layout: "clinic",
    components: ["profile", "links", "pix", "footer"],
    componentVariants: {},
    supportedFeatures: ["profile", "links", "whatsapp", "pix", "services"],
  }),
  define({
    id: "therapy-wellbeing",
    slug: "therapy-wellbeing",
    name: "Terapia e psicologia",
    description: "Um espaço acolhedor, humano e profissional para apresentar seu cuidado.",
    category: "therapy",
    badge: "Novo",
    bestFor: "terapeutas, psicólogos e profissionais do bem-estar",
    theme: {
      colors: {
        background: "#f4f1eb",
        surface: "#fffdf9",
        text: "#29433d",
        muted: "#6f8179",
        primary: "#728f7a",
      },
      typography: { fontFamily: displayFont } as ThemeTokens["typography"],
    },
    layout: "therapy",
    components: ["profile", "links", "pix", "footer"],
    componentVariants: {},
    supportedFeatures: ["profile", "links", "whatsapp", "pix", "services", "socials"],
  }),
  define({
    id: "academy-performance",
    slug: "academy-performance",
    name: "Academia",
    description: "Uma presença forte para academias, studios e personal trainers.",
    category: "academy",
    bestFor: "academias, studios e personal trainers",
    theme: {
      colors: {
        background: "#07100d",
        surface: "#102018",
        text: "#f2fff6",
        muted: "#a7c6b1",
        primary: "#48d66d",
      },
      typography: { fontFamily: displayFont } as ThemeTokens["typography"],
    },
    layout: "academy",
    components: ["profile", "links", "footer"],
    componentVariants: {},
    supportedFeatures: ["profile", "links", "whatsapp", "services"],
  }),
  define({
    id: "law-authority",
    slug: "law-authority",
    name: "Advocacia",
    description: "Apresentação sóbria e confiável para advocacia e consultoria jurídica.",
    category: "law",
    bestFor: "advogados, escritórios e consultores jurídicos",
    theme: {
      colors: {
        background: "#0b111d",
        surface: "#121b2b",
        text: "#f7f1df",
        muted: "#b9b5a9",
        primary: "#d4ad5a",
      },
      typography: { fontFamily: displayFont } as ThemeTokens["typography"],
    },
    layout: "law",
    components: ["profile", "links", "footer"],
    componentVariants: {},
    supportedFeatures: ["profile", "links", "whatsapp", "services"],
  }),
  define({
    id: "beauty-glow",
    slug: "beauty-glow",
    name: "Salão de beleza",
    description: "Delicado e sofisticado para beleza e bem-estar.",
    category: "beauty",
    theme: {
      colors: {
        background: "#fdf2f8",
        surface: "#ffffff",
        text: "#701a75",
        muted: "#a21caf",
        primary: "#c026d3",
      },
    },
    layout: "vertical",
    components: ["banner", "profile", "links", "pix", "footer"],
    componentVariants: {
      banner: "compact",
      profile: "overlapping-banner",
      links: "glass",
      pix: "highlighted",
      footer: "discreet",
    },
    supportedFeatures: ["profile", "links", "socials", "pix"],
  }),
  define({
    id: "portfolio-studio",
    slug: "portfolio-studio",
    name: "Portfólio",
    description: "Uma vitrine autoral para portfólios e projetos.",
    category: "portfolio",
    theme: {
      colors: {
        background: "#18181b",
        surface: "#27272a",
        text: "#fafafa",
        muted: "#d4d4d8",
        primary: "#facc15",
      },
    },
    layout: "creator",
    components: ["banner", "profile", "links", "footer"],
    componentVariants: {
      banner: "default",
      profile: "business",
      links: "glass",
      footer: "discreet",
    },
    supportedFeatures: ["profile", "links", "socials"],
  }),
];
